### ISSUE TITLE
Ricard > p6 > p6sawsynth.axp

### ISSUE THREAD

**Issue by ezawadzki** [axoloti/axoloti-contrib#11]
Hello,

I would like to make run p6sawsynth.axp on my axoloti board, but I got this issue :

```
/Users/.../Documents/axoloti/build/xpatch.cpp:162:20: fatal error: eeprom.h: No such file or directory
 #include <eeprom.h>

```
I tried two things to import the library in preferences, but not working :

`/Users/.../Documents/axoloti/lib/EEPROM/`

Firmware version : 1.0.0.1

Thanks for you help.

Emilie

**Comment by polluxsynth** [comment]
That's because the memory_1 object in p6sawsynth requires a special version of the Axoloti firmware, which includes an EEPROM driver for the on-board EEPROM in the P6. If you delete the memory_1 object from the patch it should work (except of course that the patch save/load functions in the menu_1 object won't work).

Note that some of the pins used by the 595ctrl, 165ctrl and lcdctrl objects in the patch may not be available on the Axoloti. I know offhand that PA8 used by 595ctrl in the patch is not available as a general I/O pin on the Axoloti, and there might be one or more of the lcdctrl pins which have the same problem. So make sure those objects refer to pins that are actually available.

**Comment by ezawadzki** [comment]
Alright thank you @polluxsynth !

**Comment by polluxsynth** [comment]
Please also note that p6sawsynth.axp is purposely designed for the P6 hardware, so it relies on there being 6 encoders and a display. The patch will work without those components, but will only play the synth patch as it is which some might consider rather boring. Or do you have similar or equivalent hardware attached to your Axoloti?

**Comment by ezawadzki** [comment]
No. I wanted to test inclusions of external c++ lib. I got the same error on my personnal patch and wanted to take a look at examples and noticed the same error in your patch. So you can close this thread.

**Comment by polluxsynth** [comment]
Ok.
